"""initial_schema

Revision ID: 20260814_0001
Revises:
Create Date: 2026-08-14 15:24:51.088620
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260814_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_state",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at_utc", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_runtime_state")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_private_chat_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("timezone_name", sa.String(), server_default="Europe/Moscow", nullable=False),
        sa.Column(
            "milestone_notifications_enabled",
            sa.Boolean(create_constraint=True, name="milestone_notifications_enabled"),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "ai_commentary_enabled",
            sa.Boolean(create_constraint=True, name="ai_commentary_enabled"),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_feedback_template_key", sa.String(), nullable=True),
        sa.Column("activated_at_utc", sa.Integer(), nullable=False),
        sa.Column("revoked_at_utc", sa.Integer(), nullable=True),
        sa.Column("created_at_utc", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", sa.Integer(), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'member')", name=op.f("ck_users_role")),
        sa.CheckConstraint("status IN ('active', 'revoked')", name=op.f("ck_users_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "telegram_private_chat_id", name=op.f("uq_users_telegram_private_chat_id")
        ),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "dashboard_state",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_chat_id", sa.Integer(), nullable=False),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column("screen_kind", sa.String(), nullable=False),
        sa.Column("active_until_utc", sa.Integer(), nullable=True),
        sa.Column("next_refresh_at_utc", sa.Integer(), nullable=True),
        sa.Column("updated_at_utc", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "screen_kind IN ('dashboard', 'history', 'record', 'settings', 'report')",
            name=op.f("ck_dashboard_state_screen_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dashboard_state_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_dashboard_state")),
    )
    op.create_table(
        "interval_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("effective_at_utc", sa.Integer(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("display_unit", sa.String(), nullable=False),
        sa.Column("created_from_update_id", sa.Integer(), nullable=True),
        sa.Column("created_at_utc", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "display_unit IN ('hour', 'day')", name=op.f("ck_interval_changes_display_unit")
        ),
        sa.CheckConstraint(
            "((interval_seconds BETWEEN 3600 AND 86400 "
            "AND interval_seconds % 3600 = 0) OR "
            "(interval_seconds BETWEEN 86400 AND 604800 "
            "AND interval_seconds % 86400 = 0))",
            name=op.f("ck_interval_changes_valid_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_interval_changes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interval_changes")),
    )
    with op.batch_alter_table("interval_changes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_interval_changes_user_effective",
            ["user_id", "effective_at_utc", "id"],
            unique=False,
        )

    op.create_table(
        "invite_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code_digest", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.Integer(), nullable=False),
        sa.Column("expires_at_utc", sa.Integer(), nullable=False),
        sa.Column("redeemed_at_utc", sa.Integer(), nullable=True),
        sa.Column("redeemed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("revoked_at_utc", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_invite_codes_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_by_user_id"],
            ["users.id"],
            name=op.f("fk_invite_codes_redeemed_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite_codes")),
        sa.UniqueConstraint("code_digest", name=op.f("uq_invite_codes_code_digest")),
    )
    with op.batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invite_codes_created_by_user_id"), ["created_by_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invite_codes_redeemed_by_user_id"), ["redeemed_by_user_id"], unique=False
        )

    op.create_table(
        "processed_updates",
        sa.Column("telegram_update_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("processed_at_utc", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('processed', 'ignored', 'rejected')",
            name=op.f("ck_processed_updates_outcome"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_processed_updates_user_id_users")
        ),
        sa.PrimaryKeyConstraint("telegram_update_id", name=op.f("pk_processed_updates")),
    )
    with op.batch_alter_table("processed_updates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_processed_updates_user_id"), ["user_id"], unique=False)

    op.create_table(
        "report_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("report_type", sa.String(), nullable=False),
        sa.Column("period_start_utc", sa.Integer(), nullable=False),
        sa.Column("period_end_utc", sa.Integer(), nullable=False),
        sa.Column(
            "is_partial", sa.Boolean(create_constraint=True, name="is_partial"), nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("claimed_at_utc", sa.Integer(), nullable=True),
        sa.Column("generated_at_utc", sa.Integer(), nullable=True),
        sa.Column("snapshot_json", sa.Text(), nullable=True),
        sa.Column("sent_at_utc", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("created_at_utc", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "report_type IN ('daily', 'weekly')", name=op.f("ck_report_deliveries_report_type")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'claimed', 'sent', 'failed', 'failed_unknown')",
            name=op.f("ck_report_deliveries_status"),
        ),
        sa.CheckConstraint(
            "period_start_utc < period_end_utc", name=op.f("ck_report_deliveries_valid_period")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_report_deliveries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_deliveries")),
        sa.UniqueConstraint(
            "user_id",
            "report_type",
            "period_start_utc",
            "period_end_utc",
            name="uq_report_deliveries_user_period",
        ),
    )
    with op.batch_alter_table("report_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_report_deliveries_status_period_end", ["status", "period_end_utc"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_report_deliveries_user_id"), ["user_id"], unique=False)

    op.create_table(
        "smoking_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at_utc", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("created_from_update_id", sa.Integer(), nullable=True),
        sa.Column("created_at_utc", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", sa.Integer(), nullable=False),
        sa.Column("deleted_at_utc", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "source IN ('now', 'backfill')", name=op.f("ck_smoking_sessions_source")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_smoking_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_smoking_sessions")),
    )
    with op.batch_alter_table("smoking_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_smoking_sessions_user_occurred_active",
            ["user_id", "occurred_at_utc", "id"],
            unique=False,
            sqlite_where=sa.text("deleted_at_utc IS NULL"),
        )

    op.create_table(
        "wake_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at_utc", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("created_from_update_id", sa.Integer(), nullable=True),
        sa.Column("created_at_utc", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", sa.Integer(), nullable=False),
        sa.Column("deleted_at_utc", sa.Integer(), nullable=True),
        sa.CheckConstraint("source IN ('now', 'backfill')", name=op.f("ck_wake_events_source")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wake_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wake_events")),
    )
    with op.batch_alter_table("wake_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_wake_events_user_occurred_active",
            ["user_id", "occurred_at_utc", "id"],
            unique=False,
            sqlite_where=sa.text("deleted_at_utc IS NULL"),
        )

    op.create_table(
        "milestone_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("basis_session_id", sa.Integer(), nullable=False),
        sa.Column("target_at_utc", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("claimed_at_utc", sa.Integer(), nullable=True),
        sa.Column("sent_at_utc", sa.Integer(), nullable=True),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("created_at_utc", sa.Integer(), nullable=False),
        sa.Column("updated_at_utc", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'claimed', 'sent', 'superseded', "
            "'skipped_stale', 'failed_unknown')",
            name=op.f("ck_milestone_notifications_status"),
        ),
        sa.ForeignKeyConstraint(
            ["basis_session_id"],
            ["smoking_sessions.id"],
            name=op.f("fk_milestone_notifications_basis_session_id_smoking_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_milestone_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_milestone_notifications")),
    )
    with op.batch_alter_table("milestone_notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_milestone_notifications_basis_session_id"),
            ["basis_session_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_milestone_notifications_status_target", ["status", "target_at_utc"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_milestone_notifications_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "report_delivery_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_delivery_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("part_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("claimed_at_utc", sa.Integer(), nullable=True),
        sa.Column("sent_at_utc", sa.Integer(), nullable=True),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.CheckConstraint(
            "part_type IN ('text', 'current_week_chart', 'history_chart')",
            name=op.f("ck_report_delivery_parts_part_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'claimed', 'sent', 'failed_unknown')",
            name=op.f("ck_report_delivery_parts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["report_delivery_id"],
            ["report_deliveries.id"],
            name=op.f("fk_report_delivery_parts_report_delivery_id_report_deliveries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_delivery_parts")),
        sa.UniqueConstraint(
            "report_delivery_id", "ordinal", name="uq_report_delivery_parts_delivery_ordinal"
        ),
    )
    with op.batch_alter_table("report_delivery_parts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_report_delivery_parts_delivery_ordinal",
            ["report_delivery_id", "ordinal"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_delivery_parts", schema=None) as batch_op:
        batch_op.drop_index("ix_report_delivery_parts_delivery_ordinal")

    op.drop_table("report_delivery_parts")
    with op.batch_alter_table("milestone_notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_milestone_notifications_user_id"))
        batch_op.drop_index("ix_milestone_notifications_status_target")
        batch_op.drop_index(batch_op.f("ix_milestone_notifications_basis_session_id"))

    op.drop_table("milestone_notifications")
    with op.batch_alter_table("wake_events", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_wake_events_user_occurred_active", sqlite_where=sa.text("deleted_at_utc IS NULL")
        )

    op.drop_table("wake_events")
    with op.batch_alter_table("smoking_sessions", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_smoking_sessions_user_occurred_active",
            sqlite_where=sa.text("deleted_at_utc IS NULL"),
        )

    op.drop_table("smoking_sessions")
    with op.batch_alter_table("report_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_deliveries_user_id"))
        batch_op.drop_index("ix_report_deliveries_status_period_end")

    op.drop_table("report_deliveries")
    with op.batch_alter_table("processed_updates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processed_updates_user_id"))

    op.drop_table("processed_updates")
    with op.batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invite_codes_redeemed_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_invite_codes_created_by_user_id"))

    op.drop_table("invite_codes")
    with op.batch_alter_table("interval_changes", schema=None) as batch_op:
        batch_op.drop_index("ix_interval_changes_user_effective")

    op.drop_table("interval_changes")
    op.drop_table("dashboard_state")
    op.drop_table("users")
    op.drop_table("runtime_state")
    # ### end Alembic commands ###
